### ISSUE TITLE
Make the serial bridge composable

### ISSUE THREAD

**Issue by clalancette** [osrf/ros2_serial_example#76]
As it stands, [ros2_serial_bridge_main.cpp](https://github.com/osrf/ros2_serial_example/blob/master/ros2_serial_example/src/ros2_to_serial_bridge_main.cpp) does way too much work.  This means that the node is not composable with other nodes.  What we should probably do here is:

1.  Remove the `signal_handler` and the `running` variable; I don't think they serve a purpose anymore.
1.  Move the `get_parameter` for `write_sleep_ms` into the constructor (or get rid of it completely).
1.  Think about how to get rid of the [rate loop](https://github.com/osrf/ros2_serial_example/blob/master/ros2_serial_example/src/ros2_to_serial_bridge_main.cpp#L58); if we code it properly, we should just be able to call `rclcpp::spin` on the constructed node.
1.  Add a dependency on `rclcpp_components` to the package.xml and CMakeLists.txt.
1.  Add the `RCLCPP_COMPONENTS_REGISTER_NODE` macro to the end of `ros2_to_serial_bridge.cpp`.
1.  Add launch files showing how to launch the node in both composable and non-composable modes.

**Comment by ahcorde** [comment]
@clalancette I reviewed all your comments. If you have some time please review https://github.com/osrf/ros2_serial_example/pull/77

I have also addressed some comments from @mjcarrol
